### ISSUE TITLE
Error opening image files with XnView MP

### ISSUE THREAD

**Issue by 1024mb** [arsenetar/dupeguru#768]
**Describe the bug**
Whenever I try to open an image file I get an error.

```
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: minimal, offscreen, webgl, windows.
```

**To Reproduce**
1. Add a folder in dupeguru containing two duplicated images
2. Scan for the dups using filename or picture mode, doesn't matter.
3. Try to open one of the duplicates

**Expected behavior**
Open the image successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 4.1.0

**Additional context**
I have reported the same issue on XnView forums but the creator told me he can't change anything so I'm posting this here.
He said this (I quote):

```
it seems that dupeGuru use Qt too, current folder should be changed to XnView when executing exe, i think
```

**Comment by arsenetar** [comment]
For step 3 I am interpreting that as you double click on one of the results to open the item?  If so dupeguru only calls `QDesktopServices.openUrl(url)`,  which results in the default program for that file being launched to open it.   The behavior after calling `QDesktopServices.openUrl(url)` is entirely dependent on Qt's implementation on windows and has no issue with other applications such as window's built-in photo viewer.  This would appear to be an issue with XnView not being compatible with being launched through windows default. The actual launching is done as:
https://github.com/qt/qtbase/blob/1ef5016bab3bce06ada14bc961a2a1db93d3060b/src/plugins/platforms/windows/qwindowsservices.cpp#L88-L90. 
Which calls the windows shell function as:
https://github.com/qt/qtbase/blob/1ef5016bab3bce06ada14bc961a2a1db93d3060b/src/plugins/platforms/windows/qwindowsservices.cpp#L67

Since dupeguru is just using the users currently selected default application through the windows API in this case we have no way to know other special requirements of the application such as "current folder should be changed to XnView when executing exe"

**Comment by 1024mb** [comment]
> For step 3 I am interpreting that as you double click on one of the results to open the item?

Yes, the context menu option "Open with...." also gives the same error.

I'm reporting this to XnView's creator. Thanks for the information.

**Comment by glubsy** [comment]
@1024mb For your information, XnViewMP opens the image just fine here on Arch Linux.

**Comment by arsenetar** [comment]
I think this might have something to do with how windows resolves dlls and the fact that both applications are using different versions of the Qt library (5.15.1 vs 5.15.2).  It seems like XnView is partially trying to use the platform plugins from dupeguru instead of its own, based on the error (list matches the plugins in the dupeguru folder and not that in the the XnView folder).  If I change the plugins available to dupeguru the list in XnView's startup error changes.  This is most likely since these dlls share the same name and the ones dupeguru is using are loaded already.  It seems like some of the Xn dlls for qt have been postfixed with Xn.

@glubsy I think your findings help point to the fact this issue is windows specific as well.

**Comment by 1024mb** [comment]
Hey guys, anything you can do? To this day this error is still present.

**Comment by arsenetar** [comment]
I don't have any further information beyond what I have already provided.  I don't see a good way to fix this as there is no way for dupeGuru to know what application is being launched or any of the specific needs of that application. My only thought on this would be to register a wrapper script as your default file handler in windows for images that takes care of changing the current folder to XnView before launching XnView with the file url passed from dupeGuru.

**Comment by StrangePeanut** [comment]
What an infuriating issue... Seems like things work just fine if any other app is set as default. Doesn't that indicate this is in fact an XnViewMP issue?

Strange how dropping a file onto the XnViewMP executable doesn't trigger the error though...

**Comment by 1024mb** [comment]
> What an infuriating issue... Seems like things work just fine if any other app is set as default. Doesn't that indicate this is in fact an XnViewMP issue?
> 
> Strange how dropping a file onto the XnViewMP executable doesn't trigger the error though...

Writing to inform you that this has been fixed in the latest version of XnViewMP.

**Comment by seascape** [comment]
Heya, new user of Dupeguru, longtime user of XnViewMP on Windows 10. Came to github to look up this error, same one as the OP's, which is still occurring when I try to have Dupeguru open an image file result. 

Sounds like it might be an XnViewMP problem to fix though...

**Comment by 1024mb** [comment]
Yeah, I don't know if this issue should be reopen. Some XnView MP updates don't have this issue and others do.

**Comment by boredboardboared** [comment]
I'm still having this issue in 2025 - has anyone found a fix?

**Comment by StrangePeanut** [comment]
> I'm still having this issue in 2025 - has anyone found a fix?

@boredboardboared make sure your XnViewMP is up to date. It was fixed Jan 2023.
